(function () {
    'use strict';

    // Stable references use the authored slide number. Runtime pagination may add
    // continuation slides, but these Lxx · Syy labels never change.
    const slideReferences = {
        'm1-programming': [1, 2], 'm1-solving': [1, 2],
        'm1-computers': [1, 3], 'm1-levels': [1, 3],
        'm1-hello': [1, 4], 'm1-toolchain': [1, 5],
        'm1-history': [1, 6], 'm1-why-cpp': [1, 6], 'm1-comments': [1, 7],

        'm2-types': [2, 2], 'm2-primitives': [2, 3], 'm2-modifiers': [2, 4],
        'm2-variables': [2, 2], 'm2-const': [2, 5],
        'm2-inference': [2, 6], 'm2-casting': [2, 7],
        'm2-operators': [3, 2], 'm2-precedence': [3, 2],
        'm2-namespaces': [3, 3], 'm2-scope': [3, 4], 'm2-storage': [3, 5],

        'm3-conditionals': [4, 2], 'm3-if-else': [4, 3],
        'm3-switch': [4, 4], 'm3-short-circuit': [4, 5], 'm3-comparison': [4, 6],
        'm3-while': [5, 2], 'm3-do-while': [5, 5],
        'm3-for': [6, 2], 'm3-loop-choice': [6, 6], 'm3-loop-pitfalls': [6, 7],

        'm4-function-anatomy': [7, 3], 'm4-parameters': [7, 5], 'm4-lambdas': [7, 7],
        'm4-reference': [8, 2], 'm4-const-reference': [8, 3],
        'm4-overloading': [8, 4], 'm4-call-stack': [8, 5],
        'm4-recursion': [8, 6], 'm4-recursive-design': [8, 6],
        'm4-complexity': [16, 7],

        'm4-arrays': [9, 2], 'm4-array-access': [9, 3],
        'm5-multidimensional': [10, 2], 'm4-vector': [10, 3],
        'm4-cstrings': [11, 7], 'm4-cstring-lib': [11, 7],
        'm4-std-string': [11, 2], 'm4-string-ops': [11, 4],
        'm4-string-io': [11, 3], 'm4-cctype': [11, 5], 'm4-string-safety': [11, 7],
        'm4-linear-search': [15, 3], 'm4-bubble-sort': [15, 4],
        'm4-binary-search': [17, 2], 'm4-merge-sort': [17, 7],

        'm4-structs': [13, 2], 'm4-struct-layout': [13, 7],
        'm6-array-records': [13, 3], 'm5-pointers': [13, 4],
        'm5-dereference': [13, 5], 'm5-arithmetic': [13, 7], 'm6-pointer-safety': [13, 5],
        'm5-static-dynamic': [14, 2], 'm5-malloc': [14, 8],
        'm5-new-delete': [14, 3], 'm6-allocation-failure': [14, 5],
        'm5-leaks': [14, 5], 'm5-smart': [14, 4],

        'm7-abstraction': [15, 2], 'm5-linked': [14, 6], 'm7-linked-ops': [14, 7],
        'm5-stack': [15, 5], 'm5-queue': [15, 6],
        'm8-bst': [17, 3], 'm7-bst-insert': [17, 4],
        'm8-heap': [17, 5], 'm7-heap-ops': [17, 6], 'm7-heap-sort': [17, 7],
        'm5-reversal': [16, 4],

        'm6-oop': [18, 2], 'm6-classes': [18, 2], 'm6-access': [18, 2],
        'm6-encapsulation': [18, 2], 'm6-constructors': [18, 3],
        'm8-constructor-types': [18, 3], 'm7-overload-ctor': [18, 3],
        'm6-destructors': [18, 5], 'm8-raii': [18, 5], 'm7-copy': [18, 4],
        'm7-operators': [18, 6], 'm7-stream': [18, 6],
        'm7-comparison': [18, 6], 'm7-assignment': [18, 4], 'm7-friend': [19, 2],

        'm8-inheritance': [19, 3], 'm8-hierarchy': [19, 4],
        'm8-access-inheritance': [20, 2], 'm8-multiple': [20, 3], 'm8-diamond': [20, 3],
        'm8-virtual': [20, 4], 'm8-polymorphism': [20, 4], 'm8-factory': [20, 6],
        'm8-container': [21, 2], 'm8-graph': [21, 4],
        'm9-system-design': [22, 2], 'm9-flight': [22, 3], 'm9-domain-classes': [22, 3],
        'm9-search': [22, 4], 'm9-sort': [22, 5], 'm9-routing': [22, 6], 'm9-patterns': [22, 7],
        'm4-permutations': [16, 5], 'm4-lcs': [16, 6],
        'm4-radix': [23, 4], 'm4-matrix': [23, 3],
        'm8-invert': [23, 5], 'm9-chess': [23, 6]
    };

    // [display term, concise definition, optional text aliases...]
    const glossary = {
        'm1-programming': ['program', 'A precise set of instructions and data a computer executes to perform a task.', 'programs'],
        'm1-solving': ['problem-solving workflow', 'A repeatable cycle of understanding, planning, implementing, testing, debugging, and refining a solution.', 'problem-solving methodology'],
        'm1-computers': ['CPU', 'The processor that fetches, decodes, and executes machine instructions while coordinating data movement.'],
        'm1-levels': ['abstraction', 'A deliberate hiding of lower-level detail behind a simpler interface or model.'],
        'm1-hello': ['entry point', 'The function where execution of a program begins; in C++, this is main.', 'main'],
        'm1-toolchain': ['toolchain', 'The connected tools that preprocess, compile, link, and run source code.', 'compile, link & run'],
        'm1-history': ['programming language', 'A formal notation for expressing instructions and data transformations a computer can execute.', 'programming languages'],
        'm1-why-cpp': ['C++', 'A statically typed, compiled, general-purpose language with direct resource control and high-level abstractions.'],
        'm1-comments': ['declaration', 'A statement that introduces a name and describes its type or interface to the compiler.', 'declarations'],

        'm2-types': ['static typing', 'A type discipline in which expression and variable types are checked before the program runs.', 'statically typed'],
        'm2-primitives': ['primitive type', 'A fundamental built-in type such as int, double, char, or bool.', 'primitive types'],
        'm2-modifiers': ['signedness', 'Whether an integer representation includes negative values or uses all bits for non-negative values.', 'signed', 'unsigned'],
        'm2-variables': ['variable', 'A named storage location whose value may change while the program executes.', 'variables'],
        'm2-const': ['const', 'A qualifier that prevents modification of an object through that name after initialization.'],
        'm2-inference': ['type inference', 'Compile-time deduction of a type from an initializer or expression.', 'auto'],
        'm2-casting': ['explicit conversion', 'A programmer-requested conversion from one type to another, such as static_cast.', 'type casting', 'static_cast'],
        'm2-operators': ['expression', 'A combination of values, names, operators, and calls that computes a value or effect.', 'expressions'],
        'm2-precedence': ['operator precedence', 'The language rules that decide which operator binds first when parentheses are absent.', 'precedence'],
        'm2-namespaces': ['namespace', 'A named scope that groups declarations and prevents collisions between identical names.', 'namespaces'],
        'm2-scope': ['scope', 'The region of source code in which a declared name is visible and can be used.'],
        'm2-storage': ['storage duration', 'The interval during program execution for which an object exists and retains storage.', 'linkage'],

        'm3-conditionals': ['condition', 'An expression converted to true or false to decide which control-flow path executes.', 'conditions'],
        'm3-if-else': ['if statement', 'A branch that executes one statement when a condition is true and optionally another when it is false.', 'if', 'else if'],
        'm3-switch': ['switch statement', 'A multi-way branch that selects a case from an integral or enumeration value.', 'switch'],
        'm3-short-circuit': ['short-circuit evaluation', 'Boolean evaluation that skips the right operand when the left operand already determines the result.', 'short-circuiting'],
        'm3-comparison': ['floating-point comparison', 'A comparison that accounts for rounding by using a suitable tolerance instead of exact equality.'],
        'm3-while': ['while loop', 'A pre-test loop that repeats while its condition remains true.', 'while'],
        'm3-for': ['for loop', 'A loop form that places initialization, continuation test, and update together.', 'for'],
        'm3-do-while': ['do-while loop', 'A post-test loop that executes its body at least once before checking its condition.', 'do-while'],
        'm3-loop-choice': ['loop invariant', 'A statement that is true before and after every completed loop iteration.', 'invariant'],
        'm3-loop-pitfalls': ['off-by-one error', 'A boundary defect where a loop executes once too many or once too few times.', 'off-by-one'],

        'm4-function-anatomy': ['function', 'A named operation with a parameter interface, body, and optional return value.', 'functions'],
        'm4-parameters': ['parameter', 'A named input or output slot in a function definition; an argument supplies its value at a call.', 'parameters', 'argument'],
        'm4-reference': ['reference', 'An alias for an existing object, written with &, that can avoid copying and permit mutation.', 'pass by reference'],
        'm4-const-reference': ['const reference', 'A read-only alias that avoids copying while preventing mutation through the parameter.', 'const&'],
        'm4-overloading': ['function overloading', 'Multiple functions sharing a name but having distinguishable parameter lists.', 'overloading'],
        'm4-lambdas': ['lambda expression', 'An unnamed callable object defined inline, optionally capturing names from its surrounding scope.', 'lambda', 'lambdas'],
        'm4-call-stack': ['call stack', 'The last-in-first-out sequence of active function frames, including parameters, locals, and return state.', 'stack frame'],
        'm4-recursion': ['base case', 'A recursive input handled directly without making another recursive call.', 'recursive case'],
        'm4-recursive-design': ['recursive decomposition', 'Solving a problem by reducing it to smaller instances of the same problem until a base case is reached.', 'recursion vs iteration'],
        'm4-complexity': ['time complexity', 'A description of how an algorithm’s operation count grows with input size.', 'space complexity', 'complexity'],

        'm4-arrays': ['array', 'A fixed-size contiguous sequence of elements of one type, accessed by integer index.', 'arrays'],
        'm4-array-access': ['index', 'An integer position used to select an element in an indexed sequence.', 'indexing', 'bounds'],
        'm5-multidimensional': ['multidimensional array', 'An array whose elements are themselves arrays, commonly used for matrices and image grids.', 'two-dimensional array'],
        'm4-vector': ['std::vector', 'A standard-library contiguous sequence that owns dynamically resizable storage.', 'vector'],
        'm4-cstrings': ['C-style string', 'A character array whose logical text ends at the first null character.', 'C-style strings', 'null terminator'],
        'm4-cstring-lib': ['cstring', 'The C++ header exposing length, copy, comparison, and concatenation operations for null-terminated character arrays.'],
        'm4-std-string': ['std::string', 'A standard-library value type that owns, sizes, and manages a sequence of characters.'],
        'm4-string-ops': ['substring', 'A contiguous portion of a string selected by position and length.', 'substr'],
        'm4-string-io': ['getline', 'An input operation that reads an entire line, including embedded spaces, up to a delimiter.'],
        'm4-cctype': ['character classification', 'Testing or transforming a character with functions such as isdigit, isalpha, and toupper.', 'cctype'],
        'm4-string-safety': ['buffer overflow', 'A write beyond the valid bounds of a storage buffer, causing undefined behavior.', 'out of bounds'],
        'm4-linear-search': ['linear search', 'A search that inspects elements sequentially until a match is found or the sequence ends.'],
        'm4-bubble-sort': ['bubble sort', 'An in-place stable sort that repeatedly swaps adjacent out-of-order elements.'],
        'm4-binary-search': ['binary search', 'A search on sorted data that repeatedly discards the half that cannot contain the target.'],
        'm4-merge-sort': ['merge sort', 'A stable divide-and-conquer sort that recursively sorts halves and merges them.'],

        'm4-structs': ['struct', 'A user-defined record type that groups named data members and optionally member functions.', 'structure'],
        'm4-struct-layout': ['alignment', 'A placement constraint requiring an object or member address to be a multiple of a boundary.', 'padding'],
        'm6-array-records': ['array of records', 'A contiguous collection in which every element is a complete structured record.', 'array of structs'],
        'm5-pointers': ['pointer', 'An object that stores the address of another object or function, or the null pointer value.', 'pointers', 'address'],
        'm5-dereference': ['dereference', 'Accessing the object designated by a valid pointer, using * or member access with ->.', 'dereferencing'],
        'm5-arithmetic': ['pointer arithmetic', 'Adding or subtracting element offsets from a pointer within the same array object.'],
        'm6-pointer-safety': ['nullptr', 'The C++ null pointer literal, used to state that a pointer designates no object.', 'null pointer'],
        'm5-static-dynamic': ['dynamic storage', 'Storage acquired during execution whose lifetime is controlled explicitly or by an owning object.', 'dynamic memory'],
        'm5-malloc': ['malloc', 'A C allocation function that reserves untyped bytes and returns a pointer that must later be passed to free.', 'calloc', 'realloc'],
        'm5-new-delete': ['new', 'A C++ expression that allocates storage and constructs an object; delete destroys and releases it.', 'delete'],
        'm6-allocation-failure': ['std::bad_alloc', 'The exception normally thrown when a C++ allocation request cannot be satisfied.', 'allocation failure'],
        'm5-leaks': ['memory leak', 'Dynamically allocated storage that remains unreachable without being released.', 'dangling pointer', 'double deletion'],
        'm5-smart': ['smart pointer', 'An object that represents pointer ownership and releases its resource automatically.', 'unique_ptr', 'shared_ptr'],

        'm7-abstraction': ['abstract data type', 'A data model defined by its valid values and operations independently of its representation.', 'ADT'],
        'm5-linked': ['linked list', 'A sequence of separately stored nodes connected by links rather than contiguous positions.'],
        'm7-linked-ops': ['list traversal', 'Following successive node links from a starting node until the end of a linked list.', 'linked-list traversal'],
        'm5-stack': ['stack', 'A last-in-first-out abstract data type with push, pop, and top operations.', 'LIFO'],
        'm5-queue': ['queue', 'A first-in-first-out abstract data type with enqueue and dequeue operations.', 'FIFO'],
        'm8-bst': ['binary search tree', 'A binary tree whose ordering invariant places smaller keys left and larger keys right.'],
        'm7-bst-insert': ['BST insertion', 'Following the search-tree ordering rule recursively or iteratively to attach a new leaf.'],
        'm8-heap': ['binary heap', 'A complete binary tree, usually stored in an array, that maintains parent–child priority order.'],
        'm7-heap-ops': ['heapify', 'Restoring the heap-order invariant by moving an element up or down the heap.', 'sift'],
        'm7-heap-sort': ['heap sort', 'An in-place comparison sort that builds a heap and repeatedly removes its extreme element.'],
        'm5-reversal': ['linked-list reversal', 'Redirecting every next link so a linked sequence is traversed in the opposite order.'],

        'm6-oop': ['object-oriented design', 'Organizing a program around objects that combine state, behavior, and explicit responsibilities.', 'object-oriented programming'],
        'm6-classes': ['class', 'A user-defined type that combines data members, member functions, and access control.', 'classes', 'object'],
        'm6-access': ['access specifier', 'A label—public, protected, or private—that controls where class members may be named.', 'private', 'protected'],
        'm6-encapsulation': ['class invariant', 'A property of an object’s state that every public operation must preserve.', 'encapsulation'],
        'm6-constructors': ['constructor', 'A special member function that establishes an object’s initial valid state.', 'constructors'],
        'm8-constructor-types': ['copy constructor', 'A constructor that creates a new object from an existing object of the same type.', 'default constructor', 'parameterized constructor'],
        'm7-overload-ctor': ['constructor overloading', 'Providing multiple constructors with different parameter lists for distinct valid initialization paths.'],
        'm6-destructors': ['destructor', 'A special member function run when an object’s lifetime ends to release owned resources.', 'destructors'],
        'm8-raii': ['RAII', 'Resource Acquisition Is Initialization: bind a resource’s lifetime to an owning object’s lifetime.'],
        'm7-copy': ['deep copy', 'A copy that duplicates owned resources so source and destination can change and be destroyed independently.', 'copy semantics', 'shallow copy'],
        'm7-operators': ['operator overloading', 'Defining the behavior of an existing C++ operator for operands of a user-defined type.'],
        'm7-stream': ['stream insertion', 'Writing a value to an output stream through operator<<; extraction reads through operator>>.', 'stream extraction'],
        'm7-comparison': ['comparison operator', 'An operator such as == or < that states equality or ordering for a value type.', 'comparison operators'],
        'm7-assignment': ['copy assignment', 'Replacing an existing object’s value from another object while preserving validity and handling self-assignment.', 'assignment operator'],
        'm7-friend': ['friend function', 'A non-member function explicitly granted access to a class’s private and protected members.', 'friend'],

        'm8-inheritance': ['inheritance', 'Defining a derived class from a base class to model a justified is-a relationship.'],
        'm8-hierarchy': ['class hierarchy', 'A directed family of base and derived classes connected by inheritance relationships.'],
        'm8-access-inheritance': ['public inheritance', 'Inheritance that preserves the base public interface and models substitutability.', 'private inheritance'],
        'm8-multiple': ['multiple inheritance', 'A class deriving directly from more than one base class.'],
        'm8-diamond': ['virtual inheritance', 'A mechanism that shares one common base subobject when a diamond-shaped hierarchy would otherwise duplicate it.', 'diamond problem'],
        'm8-virtual': ['virtual function', 'A member function whose override is selected from the object’s runtime type through dynamic dispatch.', 'virtual functions'],
        'm8-polymorphism': ['runtime polymorphism', 'Using a base interface while behavior is selected from the concrete object’s runtime type.', 'dynamic dispatch'],
        'm8-factory': ['factory', 'A construction operation that centralizes which concrete type is created and returns it through an abstraction.', 'factory pattern'],
        'm8-container': ['heterogeneous container', 'A collection that safely stores objects of different concrete types behind a shared interface.'],
        'm8-graph': ['object graph', 'Objects represented as vertices connected by relationship objects or references that act as edges.', 'polymorphic graph'],
        'm9-system-design': ['responsibility', 'A specific piece of state or behavior that a component is accountable for owning or performing.', 'cohesion', 'coupling'],
        'm9-flight': ['domain model', 'A software representation of important real-world entities, rules, and relationships in a problem domain.', 'flight booking model'],
        'm9-domain-classes': ['association', 'A modeled relationship between domain objects whose lifetimes are not necessarily owned by one another.', 'domain classes'],
        'm9-search': ['predicate', 'A function or callable that returns true or false and is used to select matching objects.', 'find_if'],
        'm9-sort': ['comparator', 'A callable that defines the ordering relation used by a sorting algorithm.', 'comparison function'],
        'm9-routing': ['route optimization', 'Selecting a path through a graph according to an objective such as minimum hops, distance, time, or cost.'],
        'm9-patterns': ['design pattern', 'A named, reusable arrangement of responsibilities that addresses a recurring design problem.', 'strategy pattern'],
        'm4-permutations': ['backtracking', 'A search technique that builds a partial candidate, recursively explores it, then undoes the choice.', 'permutation'],
        'm4-lcs': ['longest common subsequence', 'The longest sequence that appears in the same relative order in two sequences, not necessarily contiguously.', 'LCS'],
        'm4-radix': ['radix sort', 'A non-comparison sort that processes keys one digit position at a time using stable buckets.'],
        'm4-matrix': ['block-recursive multiplication', 'Matrix multiplication expressed by recursively multiplying and combining submatrices.', 'recursive matrix multiplication'],
        'm8-invert': ['tree inversion', 'Recursively or iteratively swapping every node’s left and right subtrees.', 'invert binary tree'],
        'm9-chess': ['polymorphic move generation', 'Computing legal behavior through a shared piece interface whose override depends on concrete piece type.', 'chess piece hierarchy']
    };

    // Technical vocabulary that supports the concept DAG but is not itself a
    // graph node. The lecture runtime defines the first occurrence in the
    // specified chronological lecture.
    const supplementalGlossary = [
        { id: 't-algorithm', lecture: 1, term: 'algorithm', aliases: ['algorithms'], definition: 'The finite, unambiguous sequence of steps a program carries out.' },
        { id: 't-input', lecture: 1, term: 'input', aliases: ['inputs'], definition: 'Information supplied to a program before or during execution.' },
        { id: 't-output', lecture: 1, term: 'output', definition: 'Information a program produces for a person or another system.' },
        { id: 't-window', lecture: 1, term: 'window', definition: 'A rectangular on-screen area belonging to one running application.' },
        { id: 't-application', lecture: 1, term: 'application', definition: 'A program intended to help a person perform a task.' },
        { id: 't-mouse-pointer', lecture: 1, term: 'pointer', definition: 'The on-screen marker moved by a mouse or touchpad.' },
        { id: 't-mouse', lecture: 1, term: 'mouse', definition: 'A hand-controlled device used to move the on-screen pointer and select items.' },
        { id: 't-keyboard', lecture: 1, term: 'keyboard', definition: 'A set of keys used to enter text, symbols, and commands.' },
        { id: 't-command', lecture: 1, term: 'command', aliases: ['commands'], definition: 'A textual instruction entered for the operating system or another tool to execute.' },
        { id: 't-machine-instruction', lecture: 1, term: 'machine instruction', aliases: ['machine instructions'], definition: 'A low-level operation encoded for a processor to execute directly.' },
        { id: 't-browser', lecture: 1, term: 'browser', definition: 'An application that requests and displays web pages.' },
        { id: 't-file', lecture: 1, term: 'file', aliases: ['files'], definition: 'A named unit of information stored by the operating system.' },
        { id: 't-folder', lecture: 1, term: 'folder', definition: 'A container used to organize files and other folders.' },
        { id: 't-terminal', lecture: 1, term: 'terminal', definition: 'A text interface for entering commands and reading their output.' },
        { id: 't-ram', lecture: 1, term: 'RAM', definition: 'Temporary working memory that holds active program instructions and data.' },
        { id: 't-bit', lecture: 1, term: 'bit', aliases: ['bits', 'binary'], definition: 'A binary digit whose value is zero or one.' },
        { id: 't-source', lecture: 1, term: 'source code', definition: 'Human-readable program text supplied to language tools.' },
        { id: 't-compiler', lecture: 1, term: 'compiler', definition: 'A tool that checks and translates source code into a lower-level form.' },
        { id: 't-linker', lecture: 1, term: 'linker', definition: 'A tool that combines compiled parts and resolves cross-file references.' },
        { id: 't-executable', lecture: 1, term: 'executable', definition: 'A file containing a program in a form the operating system can run.' },
        { id: 't-identifier', lecture: 1, term: 'identifier', aliases: ['identifiers'], definition: 'A programmer-chosen name for an entity such as a variable or function.' },
        { id: 't-initializer', lecture: 1, term: 'initializer', definition: 'An expression that supplies an object’s initial value.' },

        { id: 't-integer', lecture: 2, term: 'integer', aliases: ['integers'], definition: 'A whole-number value with no fractional component.' },
        { id: 't-floating', lecture: 2, term: 'floating-point', definition: 'A finite-precision representation of real-number approximations.' },
        { id: 't-boolean', lecture: 2, term: 'Boolean', definition: 'A logical value that is either true or false.' },
        { id: 't-character', lecture: 2, term: 'character', aliases: ['characters'], definition: 'One encoded text unit represented in C++ by a character type.' },
        { id: 't-range', lecture: 2, term: 'range', definition: 'The set of values a representation or operation can validly express.' },
        { id: 't-precision', lecture: 2, term: 'precision', definition: 'The amount of significant information retained by a numeric representation.' },
        { id: 't-truncation', lecture: 2, term: 'truncated', aliases: ['truncation'], definition: 'Discarding a fractional or excess part rather than rounding it.' },

        { id: 't-operator', lecture: 3, term: 'operator', aliases: ['operators'], definition: 'A symbol or keyword that specifies an operation on one or more operands.' },
        { id: 't-lifetime', lecture: 3, term: 'lifetime', definition: 'The interval during execution in which an object exists.' },
        { id: 't-global-state', lecture: 3, term: 'global state', definition: 'Mutable program data accessible beyond one narrow local owner.' },
        { id: 't-branch', lecture: 4, term: 'branch', aliases: ['branches'], definition: 'One possible control-flow path selected by a condition.' },
        { id: 't-boundary', lecture: 4, term: 'boundary test', aliases: ['boundary tests'], definition: 'A test at or immediately around the edge of a valid input region.' },
        { id: 't-tolerance', lecture: 4, term: 'tolerance', definition: 'A problem-chosen maximum acceptable numerical difference.' },

        { id: 't-iteration', lecture: 5, term: 'iteration', aliases: ['iterations'], definition: 'One execution of a loop body.' },
        { id: 't-sentinel', lecture: 5, term: 'sentinel', definition: 'A distinguished input value used to signal the end of a sequence.' },
        { id: 't-termination', lecture: 5, term: 'termination', definition: 'The point at which an algorithm or loop finishes.' },
        { id: 't-nested-loop', lecture: 6, term: 'nested loops', definition: 'A loop inside another loop, commonly used to enumerate combinations or dimensions.' },
        { id: 't-precondition', lecture: 7, term: 'precondition', aliases: ['preconditions'], definition: 'A requirement that must hold before an operation is called.' },
        { id: 't-return-value', lecture: 7, term: 'return value', aliases: ['returned result'], definition: 'The result a function sends back to its caller.' },
        { id: 't-callable', lecture: 7, term: 'callable', definition: 'An entity that can be invoked with function-call syntax.' },
        { id: 't-stack-frame', lecture: 8, term: 'stack frame', aliases: ['stack frames'], definition: 'The storage and return state associated with one active function call.' },

        { id: 't-contiguous', lecture: 9, term: 'contiguous', definition: 'Stored in adjacent memory locations without gaps between elements.' },
        { id: 't-undefined', lecture: 9, term: 'undefined behavior', definition: 'A situation for which the C++ standard imposes no required program behavior.' },
        { id: 't-matrix', lecture: 10, term: 'matrix', aliases: ['matrices'], definition: 'A rectangular arrangement of values indexed by row and column.' },
        { id: 't-null-char', lecture: 11, term: 'null character', definition: 'The zero-valued character that terminates a C-style string.' },

        { id: 't-compile-error', lecture: 2, term: 'compile-time', definition: 'The phase in which source is checked and translated before execution.' },
        { id: 't-link-error', lecture: 12, term: 'link-time', definition: 'The phase in which compiled parts are combined and external names resolved.' },
        { id: 't-runtime', lecture: 10, term: 'run-time', aliases: ['runtime'], definition: 'The period while a compiled program is executing.' },
        { id: 't-logic-error', lecture: 12, term: 'logic error', aliases: ['Logic'], definition: 'A defect where execution completes but the result violates the specification.' },
        { id: 't-test-case', lecture: 12, term: 'test case', aliases: ['test cases'], definition: 'A specified input, action, and expected result used to check behavior.' },
        { id: 't-regression', lecture: 12, term: 'regression test', definition: 'A repeatable test that protects behavior previously shown to work.' },
        { id: 't-exception', lecture: 12, term: 'exception', definition: 'A C++ mechanism for reporting a failure that interrupts normal control flow.' },

        { id: 't-address', lecture: 13, term: 'memory address', aliases: ['address'], definition: 'A location identifier used to refer to stored data.' },
        { id: 't-ownership', lecture: 14, term: 'ownership', definition: 'The responsibility for controlling a resource’s lifetime and release.' },
        { id: 't-quadratic', lecture: 15, term: 'quadratic', definition: 'Growth proportional to the square of input size, commonly written O(n²).' },
        { id: 't-memoization', lecture: 16, term: 'memoization', definition: 'Caching subproblem results so repeated states are not recomputed.' },
        { id: 't-stable-sort', lecture: 17, term: 'stable', definition: 'A sorting property that preserves the input order of equivalent elements.' },
        { id: 't-complete-tree', lecture: 17, term: 'complete binary tree', definition: 'A binary tree filled level by level, with the last level filled from left to right.' },
        { id: 't-rule-zero', lecture: 18, term: 'Rule of Zero', definition: 'Prefer member types that manage resources so no custom copy, assignment, or destructor is required.' },
        { id: 't-substitution', lecture: 19, term: 'substitutability', definition: 'The requirement that a derived object honor every promise of its public base interface.' },
        { id: 't-composition', lecture: 19, term: 'composition', definition: 'Building an object from member objects to model a has-a relationship.' },
        { id: 't-abstract-class', lecture: 20, term: 'abstract', aliases: ['abstract class'], definition: 'A class intended as an interface and not directly instantiable.' },
        { id: 't-override', lecture: 20, term: 'override', definition: 'A declaration check that a derived virtual function matches a base virtual function.' },
        { id: 't-adjacency', lecture: 21, term: 'adjacency list', definition: 'A graph representation storing the outgoing neighbors of each vertex.' },
        { id: 't-capstone', lecture: 23, term: 'capstone', aliases: ['capstones'], definition: 'An integrating task that combines several previously learned concepts.' },
        { id: 't-bucket', lecture: 23, term: 'bucket', aliases: ['buckets'], definition: 'A temporary group that collects values sharing a chosen key or digit.' }
    ];

    const lectureContexts = {
        1: { module: '01 · Computer Basics & Problem Solving', prerequisites: ['No prior computer use or programming required', 'Bring institute login details; guided help is available'], outcomes: ['Identify the computer, browser, file, folder, and terminal', 'State an input → process → output algorithm', 'Compile and run a minimal C++ program'], unlocks: 'Types, declarations, and program state' },
        2: { module: '02 · Types & Representation', prerequisites: ['A minimal C++ program', 'A declaration and initializer'], outcomes: ['Choose a primitive type from meaning and range', 'Use const and auto deliberately', 'Recognize a potentially lossy conversion'], unlocks: 'Expressions, scope, and lifetime' },
        3: { module: '02 · Expressions & Program State', prerequisites: ['Primitive values and variables', 'The compile–run cycle'], outcomes: ['Parenthesize an expression', 'Distinguish scope from storage duration', 'Explain namespace and linkage roles'], unlocks: 'Boolean decisions' },
        4: { module: '03 · Decisions', prerequisites: ['Expressions and comparisons', 'Boolean values'], outcomes: ['Translate a decision table into branches', 'Use short-circuiting as a guard', 'Design boundary tests'], unlocks: 'Condition-controlled repetition' },
        5: { module: '03 · Iteration I', prerequisites: ['Conditions', 'State updates'], outcomes: ['Trace a while loop', 'Validate with do-while', 'Identify measurable progress'], unlocks: 'Counted and nested loops' },
        6: { module: '03 · Iteration II', prerequisites: ['while and do-while', 'Conditions and updates'], outcomes: ['Trace a for loop', 'Use nested loops', 'State a loop invariant'], unlocks: 'Functions' },
        7: { module: '04 · Functions I', prerequisites: ['Types, scope, branches, and loops', 'A complete main function'], outcomes: ['Read a declaration, definition, and call', 'State a function contract', 'Use value parameters and return values'], unlocks: 'References and the call stack' },
        8: { module: '04 · Functions II', prerequisites: ['Function calls and returns', 'Scope and loop tracing'], outcomes: ['Choose value or reference parameters', 'Resolve a simple overload', 'Trace a recursive call shape'], unlocks: 'Indexed sequences' },
        9: { module: '05 · Arrays I', prerequisites: ['Counted loops', 'Function parameters'], outcomes: ['Declare a fixed array', 'Traverse its valid range', 'Explain zero-based indexing'], unlocks: 'Matrices and vectors' },
        10: { module: '05 · Arrays II', prerequisites: ['Fixed arrays', 'Nested loops'], outcomes: ['Traverse a matrix', 'Use vector size and at', 'Choose fixed or runtime size'], unlocks: 'Owned text' },
        11: { module: '05 · Strings & Text', prerequisites: ['Indexed traversal', 'Functions and const references'], outcomes: ['Process std::string safely', 'Read a complete line', 'Validate characters and bounds'], unlocks: 'Debugging and structured records' },
        12: { module: 'Integration · Debugging & Debrief', prerequisites: ['Pre-mid-semester foundations', 'An attempted solution or practice program'], outcomes: ['Classify a defect', 'Trace changing state', 'Build boundary tests from a contract'], unlocks: 'Post-mid-semester records and memory' },
        13: { module: '06 · Records & Pointers', prerequisites: ['Arrays, strings, and functions', 'Scope and lifetime'], outcomes: ['Model a record with struct', 'Trace address and dereference operations', 'Recognize invalid pointer states'], unlocks: 'Dynamic ownership' },
        14: { module: '06–07 · Dynamic Memory & Links', prerequisites: ['Records and pointers', 'Loop invariants'], outcomes: ['State an ownership rule', 'Use unique_ptr for exclusive ownership', 'Traverse a linked list'], unlocks: 'Linear abstract data types' },
        15: { module: '07 · Linear Structures & Algorithms', prerequisites: ['Arrays and linked nodes', 'Functions and loops'], outcomes: ['Choose an ADT from operations', 'Apply search and bubble sort to arrays', 'Explain stack and queue order'], unlocks: 'Recursive structures and ordered search' },
        16: { module: '04–07 · Recursive Decomposition', prerequisites: ['Call-stack preview', 'Arrays, strings, and linked nodes'], outcomes: ['Prove progress to a base case', 'Trace recursive frames', 'Compare recursive and iterative space'], unlocks: 'Trees, heaps, and recursive sorting' },
        17: { module: '07 · Ordered Structures & Algorithms', prerequisites: ['Sorted arrays and recursion', 'Linked nodes and arrays'], outcomes: ['Maintain BST and heap invariants', 'Trace binary search', 'Explain merge-sort decomposition'], unlocks: 'Object design' },
        18: { module: '08 · Object Design & Value Semantics', prerequisites: ['Records, functions, and ownership', 'Construction and lifetime motivation'], outcomes: ['Protect a class invariant', 'Distinguish copy construction from assignment', 'Use RAII and Rule-of-Zero members'], unlocks: 'Inheritance' },
        19: { module: '08–09 · Inheritance Foundations', prerequisites: ['Classes and access control', 'Value semantics'], outcomes: ['Use friend access narrowly', 'Model a justified is-a relationship', 'Prefer composition for has-a'], unlocks: 'Dynamic dispatch' },
        20: { module: '09 · Runtime Polymorphism', prerequisites: ['Class hierarchy', 'Pointers and smart ownership'], outcomes: ['Use a virtual interface', 'Delete safely through a base', 'Centralize construction with a factory'], unlocks: 'Polymorphic structures' },
        21: { module: '09 · Polymorphic Data Structures', prerequisites: ['Runtime polymorphism', 'Vectors and smart pointers'], outcomes: ['Own heterogeneous objects safely', 'Apply one algorithm through a base interface', 'Separate graph links from ownership'], unlocks: 'Applied systems' },
        22: { module: '09 · Applied Systems', prerequisites: ['Object design and collections', 'Search, sort, and graph concepts'], outcomes: ['Assign domain responsibilities', 'Apply predicates and comparators', 'Separate policy from mechanism'], unlocks: 'Capstone integrations' },
        23: { module: '09 · Capstones', prerequisites: ['Recursion, buckets, trees, and polymorphism', 'Structure selection from operations'], outcomes: ['Trace matrix, radix, and tree transformations', 'Apply polymorphism to chess pieces', 'Write an integration checklist'], unlocks: 'Independent practice and revision' }
    };

    const sessionPlans = {
        1: [1, 2, 3, 4, 5, 7, 8, 9],
        2: [1, 2, 3, 5, 6, 7, 8],
        3: [1, 2, 3, 4, 5, 6, 7, 8],
        4: [1, 2, 3, 4, 5, 6, 7, 8],
        5: [1, 2, 3, 4, 5, 6, 7, 8],
        6: [1, 2, 3, 4, 5, 6, 7, 8],
        7: [1, 2, 3, 4, 5, 6, 8],
        8: [1, 2, 3, 4, 5, 6, 7, 8],
        9: [1, 2, 3, 4, 5, 6, 7, 8],
        10: [1, 2, 3, 4, 5, 6, 7, 8],
        11: [1, 2, 3, 4, 5, 6, 8],
        12: [1, 2, 3, 4, 5, 6, 7, 8],
        13: [1, 2, 3, 4, 5, 6, 7, 8],
        14: [1, 2, 3, 4, 5, 6, 7, 9],
        15: [1, 2, 3, 4, 5, 6, 7, 8],
        16: [1, 2, 3, 4, 5, 7, 8],
        17: [1, 2, 3, 4, 5, 6, 7, 8],
        18: [1, 2, 3, 4, 5, 6, 7],
        19: [1, 2, 3, 4, 5, 6, 7, 8],
        20: [1, 2, 4, 5, 6, 7, 8],
        21: [1, 2, 3, 4, 5, 6, 7, 8],
        22: [1, 2, 3, 4, 5, 6, 7, 8],
        23: [1, 2, 3, 4, 5, 6, 7, 8]
    };

    window.CS103SlideReferences = Object.freeze(slideReferences);
    window.CS103Glossary = Object.freeze(glossary);
    window.CS103SupplementalGlossary = Object.freeze(supplementalGlossary);
    window.CS103LectureContexts = Object.freeze(lectureContexts);
    window.CS103SessionPlans = Object.freeze(sessionPlans);
}());
