// One source of truth for the generated meme slides. `afterSlide` is the
// authored slide index in the generator's zero-based `slides` array.
export const lectureMemes = {
    1: [
        { slug: 'algorithm-workflow', afterSlide: 2, title: 'A wish is not an algorithm until it has finite steps', alt: 'A student turns a tangled pile of vague sticky notes into a calm three-step path from input to process to output.', setup: 'The problem statement says "just make it work."', punchline: 'The compiler cannot execute a wish — write the finite steps first.', prompt: 'Show a student at a desk turning a tangled pile of vague sticky notes into a neat three-step path of input, process, output that leads to a tiny glowing terminal. Make the visual joke that the tangled wish pile is chaotic while the precise path is calm and executable.' },
        { slug: 'hardware-abstraction', afterSlide: 4, title: 'One line of C++ replaces a thousand hidden switches', alt: 'A student calmly writes a C++ idea while a tiny CPU robot follows a long hidden trail of machine-level steps underneath the desk.', setup: 'Student: "I want the computer to say hello." The CPU:', punchline: 'C++ gives you the idea; the hardware handles the microscopic choreography.', prompt: 'Show a student writing one simple programming idea while a tiny friendly CPU robot performs an absurdly long hidden choreography of tiny switches and instruction cards underneath the desk. The visual joke is that abstraction hides the busywork while preserving the result.' },
        { slug: 'main-observable-output', afterSlide: 6, title: 'No output, no proof the program ran', alt: 'A tiny program enters through a doorway marked by the main function and proudly turns on a visible terminal result.', setup: 'The program has one job: prove it exists.', punchline: 'Give it a main entrance and an observable result.', prompt: 'Show a tiny cheerful program character entering a small theater through a clear doorway, then turning on a glowing terminal output spotlight for the audience. The visual joke is that the program cannot take a bow until it has an entry point and a visible result.' }],
    2: [
        { slug: 'static-typing', afterSlide: 2, title: 'The compiler rejects a mislabeled value before it runs', alt: 'A friendly compiler clerk checks labeled bins for a count, temperature, grade, and yes-or-no flag before a small program starts.', setup: 'Four values arrive at the checkpoint wearing the wrong labels.', punchline: 'No value gets past the clerk without the label it actually deserves.', prompt: 'Show a friendly compiler clerk at a checkpoint inspecting four clearly different unlabeled objects—a stack of counters, a thermometer, a letter card, and a yes-or-no switch—before allowing a small program to start. No readable words or letters in the image; use shapes and symbols only.' },
        { slug: 'meaningful-types', afterSlide: 4, title: 'Four objects, four boxes — habit picks the wrong one', alt: 'A student sorts a whole-number counter, a measurement, a single character tile, and a yes-or-no switch into matching containers.', setup: 'Same-looking storage boxes, four very different meanings.', punchline: 'The meaning chooses the container; the habit just grabs the nearest one.', prompt: 'Show a student sorting four objects—a stack of whole counters, a liquid measuring tube, one colored tile, and a two-position switch—into four purpose-shaped containers. The visual joke is that one generic box keeps rejecting the mismatched objects.' },
        { slug: 'range-precision', afterSlide: 6, title: '"It is a number" is not a finished type decision', alt: 'A tiny number container overflows when asked to hold a huge range and spills a delicate fractional measurement beside it.', setup: 'A tiny container is asked to hold an enormous range and a delicate fraction at once.', punchline: 'One dimension says what fits; the other says what detail survives.', prompt: 'Show a tiny labeled-by-shape number container struggling with an enormous stack of values and a delicate fractional glass measurement, while a larger careful container handles both. Make the overflow playful and educational; no text.' }],
    3: [
        { slug: 'scope-visibility', afterSlide: 1, title: 'A helper reaches for the whole building', alt: 'A student keeps a temporary object inside a small fenced workspace while a long-lived outer object remains visible beyond the fence.', setup: 'A temporary helper tries to wander into the whole program.', punchline: 'The fence is a polite "please stay here" — nothing personal.', prompt: 'Show a student placing a temporary helper object inside a small transparent fenced work area while a needed outer object remains visible outside. The helper comically reaches for the whole building but is gently kept inside its scope. No words.' },
        { slug: 'namespace-collision', afterSlide: 5, title: 'Two labs, one tool name, one traffic jam', alt: 'Two friendly workshops each contain a tool with the same shape, separated by colored namespace doors so they do not collide.', setup: 'Two laboratories both have a tool named "completed."', punchline: 'Give each tool its own door before the names start bumping into each other.', prompt: 'Show two friendly laboratory workshops containing similar-looking tools, separated by distinct colored doorway frames so the tools can coexist peacefully instead of colliding in the hallway. The visual joke is name collision prevented by organized spaces; no text.' },
        { slug: 'expression-grouping', afterSlide: 6, title: 'Two readers, one line, two different answers', alt: 'Two students interpret the same arithmetic expression differently until one adds clear parentheses and both see the same grouped path.', setup: 'Two people read the same arithmetic line and take different routes.', punchline: 'Parentheses are the road signs of expression evaluation.', prompt: 'Show two students following different branching paths from the same arithmetic tokens on a floor, then placing large clear parentheses-shaped road signs that make both paths converge. Avoid readable text or numbers.' }],
    4: [
        { slug: 'decision-table', afterSlide: 2, title: 'The branch code says "trust me"', alt: 'A student lays out a neat grid of switches and outcomes so every combination leads to one visible result.', setup: 'The branch code says "trust me."', punchline: 'The table says: show me every row you intend to handle.', prompt: 'Show a student laying out a neat grid of two-position switches and matching outcome tokens, with every combination visibly connected to exactly one result. The visual joke is a messy branching shrub becoming a calm test matrix. No text.' },
        { slug: 'exception-first', afterSlide: 4, title: 'Every visitor wants the normal door', alt: 'A careful gatekeeper handles an emergency visitor first, then a warning visitor, and finally lets the ordinary crowd through.', setup: 'Every visitor wants to use the "normal" door.', punchline: 'Emergency first, special cases next, ordinary traffic waits its turn.', prompt: 'Show a careful gatekeeper at three doors: an emergency visitor is routed through a fast side door, a warning visitor through a second door, and a normal crowd through the wide final door. The visual joke is orderly branch priority; no signs or text.' },
        { slug: 'switch-discrete', afterSlide: 6, title: 'A switch is asked for "anything between 2.1 and 2.9"', alt: 'A small control panel cleanly selects among three distinct buttons while a sliding ramp of continuous values is sent elsewhere.', setup: 'The panel has three honest buttons and one confused ramp of values.', punchline: 'Buttons like named choices; a ramp needs a range check instead.', prompt: 'Show a cheerful control panel with three distinct physical buttons working perfectly, beside a smooth continuous ramp of values that is clearly too fluid for the buttons and is guided toward a range-checking lane. No text or numbers.' }],
    5: [
        { slug: 'while-trace', afterSlide: 2, title: 'The loop runs three times, allegedly', alt: 'A student follows three stepping stones labeled only by visual count marks toward a clear stop line, checking the condition at each step.', setup: 'The loop runs three times — allegedly.', punchline: 'Trace the state; do not negotiate with the loop after it starts.', prompt: 'Show a student stepping across a short path of three glowing state stones toward a clear stop line, looking back at each stone to verify the next condition. The visual joke is a loop trace as a literal walk. No readable text or numbers.' },
        { slug: 'progress-termination', afterSlide: 4, title: 'One robot is on a treadmill and does not know it', alt: 'A tiny robot walks toward a finish gate while one misleading treadmill sends a second robot endlessly backward.', setup: 'Both updates claim they are making progress toward the gate.', punchline: 'One is closing the distance; the other found a treadmill.', prompt: 'Show two tiny robots approaching finish gates: one moves steadily closer, while the other is trapped on a treadmill moving away from its gate. The visual joke clearly contrasts progress toward termination with a stalled or wrong-direction update.' },
        { slug: 'sentinel-input', afterSlide: 6, title: 'The input stream never announces its own length', alt: 'A stream of numbered parcels enters a processing machine and a special stop token closes the gate without entering the total pile.', setup: 'Parcels keep arriving with no manifest and no final count.', punchline: 'One special token says "we are done," then stays out of the total.', prompt: 'Show a conveyor of ordinary parcels entering a counting machine, followed by one visually distinct stop token that closes the gate and stays outside the counted pile. No text, letters, or numbers.' }],
    6: [
        { slug: 'for-parts', afterSlide: 2, title: 'Three clauses arrive at rehearsal together', alt: 'A conductor cues a tiny marching loop with a start signal, a boundary gate, and a step drumbeat all in one coordinated scene.', setup: 'The loop’s three clauses arrive at rehearsal.', punchline: 'Start, check, step — the rhythm stays where the reader can see it.', prompt: 'Show a playful conductor coordinating three visual elements in one marching rhythm: a starting flag, a boundary gate, and a repeating step drumbeat guiding a small line of tokens. The scene should make loop initialization, test, and update feel like one readable rhythm; no text.' },
        { slug: 'exact-range', afterSlide: 4, title: 'The sixth tile is feeling optimistic', alt: 'A student marks five floor tiles from the first tile through the last valid tile while a sixth tile is visibly outside the safe boundary.', setup: 'Five positions exist. The sixth tile disagrees.', punchline: 'Write the valid range first; let the bound exclude what does not exist.', prompt: 'Show a student marking a row of five safe floor tiles and a sixth tile just beyond a clear safety boundary, with a small curious robot stopping at the boundary. No text or numbers.' },
        { slug: 'nested-coordinates', afterSlide: 6, title: 'The inner loop promises it will be quick', alt: 'A tiny robot sweeps every cell of a rectangular grid, completing one row before moving to the next.', setup: 'The inner loop says it will be quick.', punchline: 'Four columns disagree, and the outer loop is still waiting.', prompt: 'Show a tiny robot methodically sweeping every cell in a rectangular grid, completing one row before moving to the next. Use a playful "one row at a time" visual rhythm and no text.' }],
    7: [
        { slug: 'function-contract', afterSlide: 2, title: 'The function is asked to do "something useful"', alt: 'A student hands a small sealed service booth its required inputs and receives one clearly defined result while a rule card keeps the promise visible.', setup: 'The function is asked to do "something useful."', punchline: 'A contract is how "something useful" becomes testable behavior.', prompt: 'Show a small friendly service booth receiving a few clearly shaped inputs, checking a simple rule card, and returning one shaped result. The visual joke is an undefined request becoming a precise contract; no readable text.' },
        { slug: 'read-signature', afterSlide: 4, title: 'A signature is a tiny sentence, if you read it in order', alt: 'A student reads a function blueprint from left to right: result slot, name badge, input slots, and a workroom.', setup: 'Four stations sit in a row: result, name, inputs, workroom.', punchline: 'Read the grammar left to right before opening the body.', prompt: 'Show a student reading a left-to-right blueprint made of four visual stations: a result container, a name badge without text, input ports, and a workroom. The composition should teach the order of a function signature without letters or numbers.' },
        { slug: 'declaration-definition', afterSlide: 6, title: 'The caller arrives before the body is finished', alt: 'A small signpost announces a service before the service room is built, allowing a caller to walk to the promised location.', setup: 'The caller arrives before the function body is finished.', punchline: 'A declaration says "this service exists"; the definition does the work later.', prompt: 'Show a construction site where a clear abstract signpost points callers toward a service booth that is still being built, while a later completed booth stands in the background. No words or logos; make the declaration-versus-definition joke visual.' }],
    8: [
        { slug: 'reference-alias', afterSlide: 2, title: 'The caller sends a value into a function — then what?', alt: 'A function helper reaches through an alias rope to adjust the same object held by the caller, while separate copies stay untouched.', setup: 'The caller sends a value into a function.', punchline: 'Copy it for a souvenir; alias it if you mean to change the original.', prompt: 'Show a caller holding one object and a function helper adjusting that exact same object through a clearly visible alias rope, while nearby duplicate copies remain unchanged. The visual joke is copy versus intentional mutation; no text.' },
        { slug: 'const-reference', afterSlide: 4, title: 'The function needs to look, not rearrange', alt: 'A function helper examines a shared object through a glass window while the object stays unchanged and no duplicate is made.', setup: 'The function needs to look, not rearrange.', punchline: '"Hands off, I am only reading" — no copy, no touch.', prompt: 'Show a function helper observing one shared object through a glass window, with hands clearly kept away and no duplicate object created. The visual joke is read-only aliasing; no text.' },
        { slug: 'overload-signatures', afterSlide: 6, title: 'Two functions want the same name badge', alt: 'Two service doors share one symbol but accept visibly different input shapes; changing only the returned package does not create a third door.', setup: 'Two functions want the same name badge.', punchline: 'Different inputs earn different doors; a different return alone does not.', prompt: 'Show two service doors with the same abstract name symbol but visibly different input slots, each routing a different shaped object. Beside them, a third door with only a different output package is rejected because its inputs are identical. No readable text.' }],
    9: [
        { slug: 'array-extent', afterSlide: 2, title: 'The array promises exactly five places', alt: 'A neat row of five identical storage slots holds one kind of object, with its fixed endpoint clearly visible.', setup: 'The array promises exactly five places.', punchline: 'Fixed means the extent is part of the object’s identity, not a suggestion.', prompt: 'Show a neat row of five identical storage slots containing the same kind of measurement object, with a firm end cap that makes the fixed extent obvious. No text or numbers.' },
        { slug: 'index-bounds', afterSlide: 4, title: 'The robot asks for "the slot after the last one"', alt: 'A small robot safely visits the first and last of five array slots while a sixth slot lies beyond a bright safety rail.', setup: 'The robot asks for "the slot after the last one."', punchline: 'There is no secret sixth element waiting off-screen.', prompt: 'Show a small robot visiting the first and last of five array slots inside a bright safety rail, while an empty sixth slot is visibly outside the rail and marked as unreachable by composition alone. No text or numbers.' },
        { slug: 'actual-bound', afterSlide: 6, title: 'The guessed endpoint points somewhere over there', alt: 'A student follows a measuring tape attached to the real end of an array instead of a guessed endpoint sign.', setup: 'A hand-drawn sign points to a vague "somewhere over there."', punchline: 'The array already knows its own size — ask it, don’t guess.', prompt: 'Show a student traversing an array while following a measuring tape physically attached to the array’s actual end; a separate guessed endpoint marker points to the wrong place and is ignored. No text.' }],
    10: [
        { slug: 'matrix-dimensions', afterSlide: 2, title: 'A matrix has rows and columns, not one mystery size', alt: 'A student navigates a rectangular grid using separate row and column rails, with both dimensions clearly guarded.', setup: 'The matrix has rows and columns, not one mysterious "size."', punchline: 'Two dimensions, two honest bounds — a ruler alone gets lost.', prompt: 'Show a student navigating a rectangular matrix with one rail along rows and another along columns, each stopping at the correct edge. The visual joke is a one-dimensional measuring stick getting confused in a 2D grid. No text or numbers.' },
        { slug: 'row-column-traversal', afterSlide: 4, title: 'The robot promises to visit every cell exactly once', alt: 'A tiny robot completes each row and each column intersection without crossing either grid boundary.', setup: 'The robot promises to visit every cell exactly once.', punchline: 'Keep both rails honest and the grid stops being a minefield.', prompt: 'Show a tiny robot visiting every intersection of a rectangular grid, completing each row and column safely without crossing either boundary. The visual joke is a robot with two synchronized boundary rails; no text.' },
        { slug: 'vector-growth', afterSlide: 6, title: 'Readings keep arriving after the plan was written', alt: 'A flexible row of connected storage tiles grows by adding a new tile while keeping the existing tiles together.', setup: 'Readings keep arriving after the plan was written.', punchline: 'A vector makes room without abandoning its contiguous neighborhood.', prompt: 'Show a flexible row of connected storage tiles growing by adding a new tile at one end while all existing tiles remain together. The visual joke is a calm expandable sequence versus a rigid fixed row. No text.' }],
    11: [
        { slug: 'string-ownership', afterSlide: 2, title: 'The text wants a home, not a loose pile of letters', alt: 'A friendly string-shaped container keeps its characters together, measures its length, and safely carries them through a program.', setup: 'The text wants a home, not a loose pile of characters.', punchline: 'One owned container tracks the storage and the size for you.', prompt: 'Show a friendly container carrying a sequence of abstract character tiles together, with a measuring ribbon and a protective lid. The visual joke is owned text having a responsible home instead of loose characters scattered everywhere. No readable letters.' },
        { slug: 'getline-spaces', afterSlide: 4, title: 'Formatted input quits at the first space', alt: 'A line of text-shaped tiles passes through a wide reader that keeps the gaps between groups instead of dropping them.', setup: 'Formatted input sees a space and thinks the line is finished.', punchline: 'The wide reader keeps the whole sentence, quiet spaces included.', prompt: 'Show a wide reader pulling an entire row of abstract text tiles through, preserving visible gaps between groups, while a narrow reader stops too early at the first gap. No readable text or letters.' },
        { slug: 'find-boundary', afterSlide: 6, title: 'The delimiter may be there — or taking the day off', alt: 'A student searches a character sequence; a found marker is safe to use, while a missing marker is stopped before it becomes an invalid position.', setup: 'The delimiter may be there. It may also be taking the day off.', punchline: 'Check the search result before slicing anything.', prompt: 'Show a student searching a row of abstract character tiles: one search finds a delimiter and safely opens a segment, another search finds nothing and is stopped by a bright guard before any slice is taken. No readable text.' }],
    12: [
        { slug: 'classify-defect', afterSlide: 2, title: 'Every bug looks like "the program is broken"', alt: 'A student sorts four bug-shaped clues into compile, link, runtime, and logic lanes before touching the code.', setup: 'Every bug looks like "the program is broken."', punchline: 'Name the defect class first; the right tool follows.', prompt: 'Show a student sorting four distinct bug-shaped clues into four clearly different lanes: a source puzzle, a missing puzzle piece, a runtime spill, and a wrong-answer compass. No words or labels; distinguish lanes by visual symbols only.' },
        { slug: 'first-diagnostic', afterSlide: 4, title: 'Ten error messages arrive at once', alt: 'A trail of warning lights leads a student to the first cracked tile, while later symptoms fade into the background.', setup: 'Ten error messages arrive at once.', punchline: 'Start with the first signal; the rest may just be echoes.', prompt: 'Show a student following a trail of warning lights to the first cracked tile in a path, while later warning lights are dim echoes behind it. The visual joke is first diagnostic as the useful clue; no text.' },
        { slug: 'state-trace', afterSlide: 6, title: 'The final answer is wrong — but where did it go wrong first?', alt: 'A student compares two parallel timelines and circles the first point where the program’s state leaves the expected path.', setup: 'The final answer is wrong, but the first wrong turn is the real evidence.', punchline: 'The earliest fork matters more than the loudest crash.', prompt: 'Show two parallel timelines of a small machine state: one expected path and one observed path, with a student identifying the first fork where they diverge. The visual joke is the earliest divergence being more useful than the final crash. No text.' }],
    13: [
        { slug: 'struct-coherent-record', afterSlide: 2, title: 'Three parallel arrays try to walk into the lab together', alt: 'A student clips an identity card, measurement dial, and validity switch into one sturdy record folder instead of carrying them separately.', setup: 'Three parallel arrays try to walk into the lab together.', punchline: 'One folder, one record — nothing has to march in formation.', prompt: 'Show a student assembling an identity card, a measurement dial, and a validity switch into one sturdy record folder, while three loose parallel piles wobble apart nearby. No readable text.' },
        { slug: 'array-records', afterSlide: 4, title: 'The lab has many readings with the same shape', alt: 'Several matching record folders line up in a tray, and a scanner visits only the valid ones.', setup: 'The lab has many readings, all the same shape.', punchline: 'Repeat the record, not the confusion between its fields.', prompt: 'Show a tray of several matching record folders, each containing the same three abstract components, while a scanner calmly visits the valid folders and skips one visibly invalid folder. No text.' },
        { slug: 'pointer-address', afterSlide: 6, title: 'The pointer arrives with a location, not a duplicate score', alt: 'A small arrow-shaped pointer points from a separate token to the one real score object located on a desk.', setup: 'The pointer arrives with a location, not a duplicate score.', punchline: 'One object, one address — the arrow just knows where to look.', prompt: 'Show a separate arrow-shaped pointer token pointing to one real score object on a desk, with no duplicate object beside the pointer. The visual joke is location versus copy; no text or numbers.' }],
    14: [
        { slug: 'ownership-lifetime', afterSlide: 2, title: 'The room closes while the object is still alive', alt: 'A small object leaves a temporary room and safely follows an owner carrying a key, while an unowned object drifts toward a leak.', setup: 'The local scope closes while the dynamic object is still alive.', punchline: 'Someone has to carry the key if the object can outlive the room.', prompt: 'Show a small object leaving a temporary room as its door closes, safely following a clear owner carrying a key, while a second unowned object drifts toward a dark leak. Supportive educational tone; no text.' },
        { slug: 'new-delete-match', afterSlide: 5, title: 'The release tool claims it works for everything', alt: 'A mechanic pairs one tool for a single object with one matching release tool, while an array of objects waits for a different paired tool.', setup: 'The release tool claims it works for everything.', punchline: 'Allocation and release are a matched pair, not a guessing game.', prompt: 'Show a friendly mechanic pairing a single-object allocation tool with its matching release tool and a separate array allocation tool with a different matching release tool. A mismatched tool is gently rejected. No text or symbols that look like code.' },
        { slug: 'unique-ptr-release', afterSlide: 7, title: 'Who remembers to release this resource?', alt: 'A single caretaker holds the only key to a resource and automatically returns it when leaving the room, while no forgotten resource is left behind.', setup: 'The resource asks who will remember to release it.', punchline: '"I own it," says the caretaker, then cleans up on the way out.', prompt: 'Show one caretaker holding the only key to a resource, then automatically returning it to a storage cabinet as the caretaker exits. The scene should communicate exclusive ownership and automatic cleanup; no text or logos.' }],
    15: [
        { slug: 'adt-operations', afterSlide: 2, title: 'What does the data structure look like?', alt: 'A student writes a small set of action tokens for a container, while the container’s internal shape remains behind a curtain.', setup: 'The student asks what the data structure looks like.', punchline: 'What it promises to do comes first; the costume can wait.', prompt: 'Show a student defining a small set of action tokens for a mysterious container—add, remove, inspect—while the container’s internal mechanism stays behind a curtain. The visual joke is operations before representation; no text.' },
        { slug: 'linear-search', afterSlide: 4, title: 'The shelf is unsorted and gives no hints', alt: 'A careful student checks items one by one along an unsorted shelf and finds the target without making assumptions about where it should be.', setup: 'The shelf is unsorted and the target refuses to give hints.', punchline: 'Check each item — boring is a reliable baseline.', prompt: 'Show a careful student checking items one by one along a completely unsorted shelf until the target is found, while a flashy shortcut arrow points nowhere useful. Supportive classroom humor; no text.' },
        { slug: 'bubble-quadratic', afterSlide: 6, title: 'Every neighbor on the shelf has an opinion', alt: 'A patient student repeatedly swaps neighboring out-of-order tiles along a row, one small adjacent trip at a time, never skipping ahead.', setup: 'The list is almost sorted, except every neighbor disagrees with the one beside it.', punchline: 'Only adjacent swaps, over and over — simple, patient, and quadratic.', prompt: 'Show a patient student repeatedly swapping only two neighboring out-of-order tiles at a time along a long row, taking many small adjacent trips rather than any long-distance move. The visual joke is that every fix travels exactly one position; no text or numbers.' }],
    16: [
        { slug: 'call-stack-frames', afterSlide: 2, title: 'The first call asks a smaller call for help', alt: 'A stack of friendly transparent frames grows as each smaller task is handed to the next frame, then unwinds in reverse order.', setup: 'The first call asks a smaller call for help.', punchline: 'Every unfinished call waits on the stack until the smallest one comes home.', prompt: 'Show a stack of friendly transparent call frames growing as each frame hands a smaller task to the next, then unwinding in reverse order. The visual joke is recursive waiting as a tidy stack; no text.' },
        { slug: 'recursive-progress', afterSlide: 4, title: 'Recursion promises it will stop "eventually"', alt: 'A series of smaller stepping stones leads a recursive character toward a clear base-case finish platform.', setup: 'Recursion promises it will stop eventually.', punchline: '"Eventually" needs a stone that is measurably smaller each time.', prompt: 'Show a recursive character crossing a sequence of visibly shrinking stepping stones toward a clear finish platform, with every step measurably smaller. The visual joke is progress toward a base case; no text or numbers.' },
        { slug: 'recursive-reversal', afterSlide: 6, title: 'The head says the rest of the list can handle itself', alt: 'A linked chain bends backward one connection at a time as each returning helper rewires its local link.', setup: 'The head says the rest of the list can handle itself.', punchline: 'It comes back, rewires one link, and trusts the rest was handled.', prompt: 'Show a linked chain being reversed one connection at a time as a helper travels to the end and each returning step rewires exactly one local link. Make the recursion structure visually clear; no text.' }],
    17: [
        { slug: 'binary-search-halves', afterSlide: 2, title: 'One middle question at a time on a very long shelf', alt: 'A student checks the middle of a sorted row and calmly shades away half the impossible tiles after each comparison.', setup: 'The sorted shelf is long, but the target gets one middle-question at a time.', punchline: 'One comparison deletes half the search space.', prompt: 'Show a student checking the middle tile of a sorted row, then calmly shading away half the impossible tiles after each comparison. The visual joke is search space shrinking dramatically; no text or numbers.' },
        { slug: 'bst-order', afterSlide: 4, title: 'The tree has one rule and refuses to break it', alt: 'A branching tree arranges smaller abstract tokens to the left and larger tokens to the right, with the same rule repeated below.', setup: 'The tree has one rule and refuses to break it locally.', punchline: 'Every subtree keeps the same ordering promise, no exceptions.', prompt: 'Show a friendly branching tree arranging small abstract tokens to the left and large tokens to the right, with the same ordering pattern repeated at every branch. No numbers or readable labels.' },
        { slug: 'heap-priority', afterSlide: 6, title: 'The queue has many tasks and one needs attention first', alt: 'A pyramid-shaped heap places the most urgent glowing token at the top while lower-priority tokens settle beneath it.', setup: 'The queue has many tasks and one needs attention first.', punchline: 'The root stays visible; everyone else waits their turn.', prompt: 'Show a pyramid-shaped heap of task tokens with the most urgent glowing token at the root and calmer tokens below, while a small scheduler reaches for the top item. No text or numbers.' }],
    18: [
        { slug: 'class-invariant', afterSlide: 1, title: 'The caller asks to reach inside and "just change the value"', alt: 'A sturdy class-shaped workshop keeps its internal gauge behind a wall and exposes only a safe control that maintains the gauge rule.', setup: 'The caller asks to reach inside and "just change the value."', punchline: 'Use the safe control — the invariant lives behind that wall.', prompt: 'Show a sturdy workshop with an internal gauge behind a wall and one safe external control that keeps the gauge within a healthy zone. A curious caller is gently redirected to the control. No text.' },
        { slug: 'constructor-state', afterSlide: 3, title: 'The object wants in before anyone checks it', alt: 'A constructor caretaker checks and sets a new object’s gauges before rolling it onto the program floor.', setup: 'The object wants to enter the program before it has been checked.', punchline: 'Construction is the entrance inspection, not a formality.', prompt: 'Show a caretaker inspecting and setting gauges on a brand-new object before rolling it through an entrance gate into a program floor. The visual joke is constructor as a pre-use safety inspection; no text.' },
        { slug: 'copy-assignment', afterSlide: 5, title: 'Two operations both look like "put this value there"', alt: 'One workshop builds a new duplicate object while another swaps the contents of an already existing object, making the two actions visibly different.', setup: 'Two operations both look like "put this value there."', punchline: 'One workshop builds a newcomer; the other renovates a resident.', prompt: 'Show two side-by-side workshops: one creates a new duplicate object from a model, while the other replaces the contents of an already existing object. Make the visual distinction obvious; no text.' }],
    19: [
        { slug: 'friend-narrow-access', afterSlide: 2, title: 'A helper asks for the master key to the whole workshop', alt: 'A class workshop opens one small side hatch to a trusted helper while the main public door remains the normal entrance.', setup: 'A helper asks for the master key to the whole workshop.', punchline: 'One narrow hatch, not a second front door.', prompt: 'Show a secure workshop with one small side hatch opened to a trusted helper while the large public door remains the normal route. The visual joke is narrow friend access versus a public interface; no text or locks with brand-like marks.' },
        { slug: 'substitutability', afterSlide: 4, title: 'The specialized vehicle calls itself an "is-a" version', alt: 'A smaller specialized vehicle safely takes the same marked route and fulfills the same stops as the base vehicle it replaces.', setup: 'The specialized vehicle calls itself an "is-a" version of the base.', punchline: 'Then it has to keep every stop the original route promised.', prompt: 'Show a specialized vehicle taking the same route and fulfilling the same stops as a larger base vehicle, with passengers staying confident. The visual joke is substitutability as keeping the whole route promise; no text.' },
        { slug: 'hierarchy-promises', afterSlide: 6, title: 'The family tree wants to share what is genuinely common', alt: 'A clear family tree branches from one shared base promise into two specialized but compatible shapes.', setup: 'The family tree wants to share what is genuinely common.', punchline: 'Trunk carries the shared promise; branches earn their specialty.', prompt: 'Show a clean branching family tree of abstract object shapes: one sturdy common base trunk, then two specialized branches that visibly retain the shared structure. No text or symbols.' }],
    20: [
        { slug: 'inheritance-interface', afterSlide: 2, title: 'Two inheritance arrows look identical from far away', alt: 'Two doors from a base workshop lead to different audiences: one public route preserves the shared entrance, while the private route stays inside the implementation area.', setup: 'Two inheritance arrows look identical from far away.', punchline: 'Up close, only one door lets outsiders through at all.', prompt: 'Show a base workshop with two clearly different routes: one public path opens to outside callers and preserves the shared entrance, while one private path remains inside the workshop. No text or labels.' },
        { slug: 'diamond-base', afterSlide: 4, title: 'The diamond has two routes to the same ancestor', alt: 'Two upper paths merge into one shared central foundation instead of building duplicate foundations beneath a diamond-shaped structure.', setup: 'The diamond has two routes to the same ancestor.', punchline: 'Share the foundation, or the structure quietly gets two of them.', prompt: 'Show a diamond-shaped structure whose two upper paths merge into one shared central foundation, with a duplicate-foundation version wobbling beside it. No text, keep it as an abstract educational diagram illustration.' },
        { slug: 'virtual-dispatch', afterSlide: 6, title: 'The controller asks for one action, not one type', alt: 'One controller sends the same request through a common interface and different runtime-shaped objects respond with their own behavior.', setup: 'The controller asks for one operation without knowing the concrete type.', punchline: 'The object picks its own override; the caller never had to ask.', prompt: 'Show one controller sending the same abstract request through a common interface to three differently shaped objects, each producing a distinct appropriate action. The visual joke is dynamic dispatch; no text or labels.' }],
    21: [
        { slug: 'heterogeneous-container', afterSlide: 2, title: 'The objects do not match in shape, but they share a promise', alt: 'One sturdy container safely holds several different shaped objects while each still exposes the same handle for a shared operation.', setup: 'The objects do not match in shape, but they do share a promise.', punchline: 'Many shapes, one handle, one ownership rule for all of them.', prompt: 'Show a sturdy container holding several visibly different abstract objects, each with the same simple handle for one shared operation. The visual joke is varied shapes with uniform ownership and interface; no text.' },
        { slug: 'interface-algorithm', afterSlide: 4, title: 'The algorithm asks for an operation, not a family photo', alt: 'A reusable conveyor accepts several differently shaped objects because it uses the same handle and never inspects their hidden interiors.', setup: 'The algorithm asks for an operation, not a family photo.', punchline: 'Promise the operation, and the machine never opens the box.', prompt: 'Show a reusable conveyor or algorithm machine accepting several differently shaped objects through one common handle without opening them up. The visual joke is interface-based reuse; no text.' },
        { slug: 'graph-relationships', afterSlide: 6, title: 'The links know who is connected, not who owns whom', alt: 'Several entity nodes sit independently while colored links describe roads between them without becoming owners of the nodes.', setup: 'The links know who is connected, not who owns whom.', punchline: 'A relationship map, not an ownership receipt.', prompt: 'Show several independent entity nodes with colored links describing roads between them; the links visibly connect but do not contain or own the nodes. The visual joke is relationships versus ownership; no text.' }],
    22: [
        { slug: 'single-responsibility', afterSlide: 2, title: 'One giant object volunteers for every responsibility', alt: 'A student sorts route, passenger, booking, and policy pieces into separate focused workstations instead of one overloaded desk.', setup: 'One giant object volunteers for every responsibility.', punchline: 'Split the reasons to change before the desk collapses.', prompt: 'Show a student sorting four kinds of domain pieces into four focused workstations instead of one overloaded desk: route, passenger, association, and policy. The visual joke is single responsibility bringing order; no text.' },
        { slug: 'domain-model', afterSlide: 4, title: 'The real world arrives with too many details', alt: 'A student turns a real-world scene into a small set of coherent object cards connected by clear association lines.', setup: 'The real world arrives with too many details.', punchline: 'Keep what affects the decision; leave the wallpaper out.', prompt: 'Show a student turning a busy real-world travel scene into a small set of coherent abstract object cards connected by clear association lines, while irrelevant background details fade away. No readable text.' },
        { slug: 'predicate-selection', afterSlide: 6, title: '"Does this object match the route?"', alt: 'A small yes-or-no filter checks each flight-shaped object and sends matching ones down a chosen lane.', setup: 'The question is "does this object match the route?"', punchline: 'Make the question callable, and the filter is reusable everywhere.', prompt: 'Show a small yes-or-no filter checking each flight-shaped object and sending matching ones down a selected lane while nonmatches wait aside. The visual joke is a domain question becoming a reusable predicate; no text.' }],
    23: [
        { slug: 'operation-structure', afterSlide: 2, title: 'The data structure asks what the program needs to do', alt: 'A student chooses among a bucket rack, tree, matrix, and hierarchy only after identifying the operation each must support.', setup: 'The data structure asks what the program needs to do.', punchline: 'Choose the tool from the operation, not from its popularity.', prompt: 'Show a student choosing among four abstract structures—a bucket rack, branching tree, tiled matrix, and hierarchy—after inspecting four different operation-shaped tasks. The visual joke is requirements choosing representation; no text.' },
        { slug: 'matrix-recursion', afterSlide: 4, title: 'The matrix is too large for one bite', alt: 'A large tiled matrix breaks into four smaller matching blocks that recursively produce partial products and recombine into one result.', setup: 'The matrix is too large for one bite.', punchline: 'Cut it into compatible blocks, solve the small ones, recombine.', prompt: 'Show a large tiled matrix breaking into four smaller matching blocks, with a recursive trail of smaller block products recombining into one finished matrix. The visual joke is divide, solve, recombine; no text or numbers.' },
        { slug: 'stable-radix-buckets', afterSlide: 6, title: 'Equal items still remember who arrived first', alt: 'A row of equal-priority tokens enters digit-based buckets and returns in the same relative order after each pass.', setup: 'The current digit decides the bucket for each item.', punchline: 'Sort by one position without shuffling the ties out of order.', prompt: 'Show a row of tokens entering several colored buckets by one visual digit-like attribute, then returning in the same relative order for matching attributes. The visual joke is stable collection preserving ties; no readable text or numbers.' }]
};

export const lectureMemeCount = Object.values(lectureMemes).reduce((total, memes) => total + memes.length, 0);
